front = "how is varchar and TEXT types in postgres different regarding length?"
back = "with varchar, the length must be specified, with TEXT, it's unbounded"
id = "fda1f605-b201-4a47-b4e6-79e0114477fd"
