front = "what does it mean for a database to be managed?"
back = "it means the infra/maintenace stuff is handled by a service provider (e.g. aws/google cloud)"
id = "821d09b5-44cd-4836-8be1-f920d5fd936c"
