front = "what is the prctl command about?"
back = "The prctl command in Linux is used to control specific characteristics of a process, like setting process name, enabling core dumps, or adjusting other process-related settings."
id = "39fcf38a-1a5c-4980-b353-2977a98c66d0"
