front = "what secret is generated before the user gets redirected when starting oauth flow?"
back = "the pkce code verifier"
id = "b0d0e99f-05f8-420d-a533-f8dc4ed6a88f"
dependencies = ["5ae84a9c-68a3-4e0d-9fa5-254a1af2d9b2", "9cc4af30-30fa-4022-9b1b-c75b43466513"]
