front = "what is the client's credentials in oauth flow?"
back = " the client_id and the client secret"
id = "30c4b10b-16e5-4c6b-8eb5-afeb0a30803c"
dependencies = ["d45bca8e-1ee6-417d-adab-94899899665e", "fbaa4975-4a07-4365-8cc2-9ce93f202d7b"]
