front = "what is an AJAX request?"
back = "a technique that allows web pages to esnd and receive data from a server asynchronously without reloading the entire page"
id = "6af7ba48-abd2-4282-bb81-c19a3fa96bf5"
