front = "what is authorization?"
back = "Authorization is the process of determining whether a user or system has the right to access a specific resource or perform an action"
id = "a562c2e4-b441-4584-8f20-1b6b29632331"
