front = "what is memcache?"
back = "Memcache is a distributed in-memory caching system used to speed up web applications by storing frequently accessed data in memory, reducing database load."
id = "a2b35796-4008-47f5-8a16-7e01efe500c2"
