front = "whats a logspool?"
back = "A logspool is a storage area where system logs or event logs are temporarily collected before being processed or sent to their final destination."
id = "323b7007-2364-4586-9615-9999bf3a608a"
