front = "what is an endpoint?"
back = "An endpoint is a specific URL or address where an API or service can be accessed by clients to send or receive data."
id = "5a612710-fe21-4ba4-bec6-346029ea2a88"
