front = "what is a sidecar?"
back = "A sidecar is a separate container or process that runs alongside a main application, typically in microservices architectures, to handle auxiliary tasks like logging, monitoring, or networking."
id = "e74ea482-bd04-43f8-a7c2-ac8f7af041f0"
