front = "why does the client send the hash of the pkce code veirfire instead of the secret itself?"
back = "cause its being sent through the front channel"
id = "f9ae2907-5d95-433c-af6f-c6fefec3c3e2"
dependencies = ["5ae84a9c-68a3-4e0d-9fa5-254a1af2d9b2", "a979788e-3056-4b47-80d0-06867b443595"]
