front = "wrt oauth, where is the only place hte user will enter their password?"
back = "at the authorization server"
id = "b8165c94-55fa-4246-a6c6-fea1a8a1f537"
dependencies = ["63b482fd-d85d-4ec6-b9cc-3a82c7202d7a", "9cc4af30-30fa-4022-9b1b-c75b43466513"]
